# Generated by Django 4.2.1 on 2023-05-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profile_image/')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Famale')], max_length=1)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_of_birth', models.DateField()),
                ('is_resign', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='positions.positions')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
