# Generated by Django 4.2.1 on 2023-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_position_employees_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
