# Generated by Django 4.2.1 on 2023-05-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employees_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='avatar_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
